const stations = {
  amazingradiouk: {
    artist: "included.1.attributes.radio_artist",
    song: "included.1.attributes.radio_name",
    album: "",
    albumArt: "included.1.attributes.image_urls.large",
    stationName: "Amazing Radio UK",
    location: "Newcastle, UK 🇬🇧",
    webUrl: "https://amazingradio.com",
    streamUrl: "https://stream.amazingradio.com:8443/stream.mp3?ngsw-bypass",
    apiUrl: "https://api.amazingtunes.com/radio/uk/airplays?page[size]=1&include[]=tune&include[]=tune.artist",
    needPath: true,
  },  
  amazingradious: {
    artist: "included.1.attributes.radio_artist",
    song: "included.1.attributes.radio_name",
    album: "",
    albumArt: "included.1.attributes.image_urls.large",
    stationName: "Amazing Radio US",
    location: "United States",
    webUrl: "https://amazingradio.com",
    streamUrl: "https://stream3.amazingradio.us:8443/stream.mp3?redirected=1",
    apiUrl: "https://api.amazingtunes.com/radio/us/airplays?page[size]=1&include[]=tune&include[]=tune.artist",
    needPath: true,
  }, 
  bagelradio: {
    stationName: "Bagel Radio",
    location: "Forest Hills, NY 🇺🇸",
    webUrl: "https://www.bagelradio.com",
    streamUrl: "https://ais-sa3.cdnstream1.com/2606_128.aac",
    apiUrl: "https://scraper2.onlineradiobox.com/us.bagel?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  bbcradio6: {
    stationName: "BBC6 Radio",
    location: "London, UK 🇬🇧",
    webUrl: "https://www.bbc.co.uk/sounds/play/live:bbc_6music",
    streamUrl: "https://a.files.bbci.co.uk/ms6/live/3441A116-B12E-4D2F-ACA8-C1984642FA4B/audio/simulcast/hls/nonuk/audio_syndication_low_sbr_v1/cfs/bbc_6music.m3u8",
    apiUrl: "https://scraper2.onlineradiobox.com/uk.bbcradio6?l=0",
    timestamp: "updated",
    orbPath: true,
  },  
  birchstreet: {
    artist: "iArtist",
    song: "iName",
    album: "",
    albumArt: "iImg",
    stationName: "Birch Street Radio",
    location: "Richmond Hill, ON 🇨🇦",
    webUrl: "https://www.birchstreetradio.com",
    streamUrl: "https://jenny.torontocast.com:8172/stream",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.birchstreet?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  chillfiltr: {
    stationName: "CHILLFILTR",
    albumArt: "iImg",
    location: "Ottawa, ON 🇨🇦",
    webUrl: "https://www.chillfiltr.com",
    streamUrl: "https://ais-edge102-live365-dal02.cdnstream.com/a80518",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.chillfiltr?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  chly: {
    stationName: "CHLY",
    location: "Nanaimo, BC 🇨🇦",
    webUrl: "https://www.chly.ca/",
    streamUrl: "http://184.69.114.194:8000/stream.mp3",
    apiUrl: "https://widgets.spinitron.com/widget/now-playing-v2?callback=_spinitron05891577247031242171657762111&station=chly&num=0&sharing=0&player=0&cover=0&merch=0&meta=0",
    timezone: "",
    stringPath: true,
    filter: ["CHLY"],
  },
  cjiq: {
    stationName: "CJIQ",
    albumArt: "iImg",
    location: "Kitchener, ON 🇨🇦",
    webUrl: "https://www.cjiqfm.com",
    streamUrl: "https://conestoga.leanstream.co/CJIQFM",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.cjiq",
    timestamp: "updated",
    orbPath: true,
    flipMeta: true,
  },
  cjmp: {
    stationName: "CJMP",
    albumArt: "iImg",
    location: "Powell River, BC 🇨🇦",
    webUrl: "https://www.cjmp.ca",
    streamUrl: "https://🇺🇸2.fastcast4u.com/proxy/terjoyce?mp=/1&1641764578515&1717635950075",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.cjmp",
    timestamp: "updated",
    orbPath: true,
    filter: ["CJMP"],
  },
  ckua: {
    artist: "0.TPE1",
    song: "0.TIT2",
    album: "0.TALB",
    stationName: "CKUA",
    location: "Edmonton, AB 🇨🇦",
    webUrl: "https://www.ckua.com",
    streamUrl: "https://ais-sa1.streamon.fm/7000_48k.aac",
    apiUrl:
      "https://yp.cdnstream1.com/metadata/7000_48k/current.json?cb=308869",
    needPath: true,
    timestamp: "0.last_seen",
  },
  coloradosound: {
    stationName: "The Colorado Sound",
    albumArt: "iImg",
    location: "Greeley, CO 🇺🇸",
    webUrl: "https://coloradosound.org",
    streamUrl: "https://ais-sa1.streamon.fm/7891_96k.aac",
    apiUrl: "https://scraper2.onlineradiobox.com/us.kjac?l=0",
    timestamp: "updated",
    orbPath: true,
    filter: ["The Colorado Sound"],
  },
  d1alt: {
    albumArt: "iImg",
    stationName: "D1 Alternative",
    location: "Toronto, ON 🇨🇦",
    webUrl: "https://d1alternative.com",
    streamUrl: "https://cast1.torontocast.com:2545/stream",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.d1alternative",
    orbPath: true,
    filter: ["D1 Alternative"],
  },
  d2relax: {
    albumArt: "iImg",
    stationName: "D2 Relax",
    location: "Toronto, ON 🇨🇦",
    webUrl: "https://d2relax.com",
    streamUrl: "https://cast1.torontocast.com:1515/stream",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.d2relax",
    orbPath: true,
    filter: ["D2 Relax"],
  },
  dkfm: {
    albumArt: "iImg",
    stationName: "DKFM",
    location: "Los Angeles, CA 🇺🇸",
    webUrl: "https://www.decayfm.com",
    streamUrl: "https://kathy.torontocast.com:2005/stream",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.dkfmshoegazeradio",
    orbPath: true,
    filter: ["ID/PSA", "DKFM"],
  },
  dkfmclassic: {
    albumArt: "iImg",
    stationName: "DKFM Classic",
    location: "Toronto, ON 🇨🇦",
    webUrl: "https://www.decayfm.com",
    streamUrl: "https://radio.streemlion.com:4245/stream",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.dkfmclassic",
    orbPath: true,
  },
  eightradio: {
    stationName: "8Radio",
    albumArt: "iImg",
    location: "Dublin, IE 🇮🇪",
    webUrl: "https://8radio.com",
    streamUrl: "https://stream.rcast.net/66127",
    apiUrl: "https://scraper2.onlineradiobox.com/ie.8radio",
    timestamp: "updated",
    pathRegex: /^(.*?)s*-s*(.*?)$/,
    orbPath: true,
    filter: ["8radio", "8Radio.com"],
  }, 
  flashAlt: {
    stationName: "Flashback Alternatives",
    albumArt: "iImg",
    location: "Toronto, ON 🇨🇦",
    webUrl: "https://flashbackalternatives.com/",
    streamUrl: "https://puma.streemlion.com:1225/stream",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.falternatives",
    timestamp: "updated",
    orbPath: true,
    filter: ["Sensoria Radio"],
  },
  funkymoose: {
    stationName: "Funky Moose Radio",
    albumArt: "iImg",
    location: "Prince Albert, SK 🇨🇦",
    webUrl: "https://funkymooseradio.ca/",
    streamUrl: "https://listen.funkymooseradio.ca/radio/8000/radio.aac",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.funkymoose?l=0",
    timestamp: "updated",
    orbPath: true,
    filter: ["Funky Moose", "funkymoosedigital.ca"],
  },
  gorillafm: {
    stationName: "Gorilla FM",
    location: "Zug, CH 🇨🇭",
    albumArt: "iImg",
    webUrl: "https://www.1.fm/station/gorillafm",
    streamUrl: "https://strm112.1.fm/gorillafm_mobile_mp3",
    apiUrl: "https://scraper2.onlineradiobox.com/ch.1fmgorillafmradio?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  theindependent: {
    stationName: "The Independent",
    location: "Jacksonville, FL 🇺🇸",
    albumArt: "iImg",
    webUrl: "https://wjct.org/jaxmusic/the-independent/",
    streamUrl: "https://18373.live.streamtheworld.com/WJCT_HD4.mp3",
    apiUrl: "https://scraper2.onlineradiobox.com/us.wjcthd4?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  indie1023: {
    artist: "0.artist",
    song: "0.title",
    album: "0.album",
    artist2: "1.artist",
    song2: "1.title",
    stationName: "Indie 102.3",
    location: "Denver, CO 🇺🇸",
    webUrl: "https://indie1023.org",
    streamUrl: "https://stream1.cprnetwork.org/cpr3_lo",
    apiUrl: "https://playlist.cprnetwork.org/won_plus3/KVOQ.json",
    needPath: true,
    altPath: true,
  },
  indie617: {
    stationName: "indie617",
    albumArt: "iImg",
    location: "Boston, MA 🇺🇸",
    webUrl: "https://offthedialmedia.com",
    streamUrl: "https://s5.radio.co/s36d03408d/listen",
    apiUrl: "https://scraper2.onlineradiobox.com/us.indie617?l=0",
    timestamp: "updated",
    orbPath: true,
    filter: ["Indie617", "Boston Calling", "LVOV Vodka", "Glassman", "Lawyers"],
  },
  indie88: {
    stationName: "Indie88",
    albumArt: "iImg",
    location: "Toronto, ON 🇨🇦",
    webUrl: "https://indie88.com",
    streamUrl: "https://cob-ais.leanstream.co/CINDFM-MP3",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.cind?l=0",
    timestamp: "updated",
    orbPath: true,
    flipMeta: true,
  },
  indiediscotheque: {
    stationName: "Indie Discotheque",
    albumArt: "iImg",
    location: "Detroit, MI 🇺🇸",
    webUrl: "https://indiediscotheque.com/",
    streamUrl: "https://radio.howtojointheindiediscothequewaitlist.com/stream.ogg",
    apiUrl: "https://scraper2.onlineradiobox.com/us.indiediscotheque?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  indieradio: {
    artist: "data.0.artist",
    song: "data.0.title",
    album: "data.0.album",
    stationName: "IHeartRadio Indie Radio",
    location: "United States 🇺🇸",
    webUrl: "https://www.iheart.com/live/indie-radio-7189/",
    streamUrl: "https://n15a-e2.revma.ihrhls.com/zc7189",
    apiUrl: "https://ca.api.iheart.com/api/v3/live-meta/stream/7189/trackHistory?limit=1",
    timestamp: "data.0.endTime",
    needPath: true,
  },
  indiexfm: {
    artist: "results.0.author",
    song: "results.0.title",
    album: "results.0.album",
    albumArt: "results.0.img_large_url",
    stationName: "Indie X FM",
    location: "Los Angeles, CA 🇺🇸",
    webUrl: "https://indiexfm.com/",
    streamUrl: "https://kathy.torontocast.com:2145/stream",
    apiUrl: "https://kathy.torontocast.com:1150/api/v2/history/?limit=1&offset=0&server=1&format=json",
    timestamp: "results.0.ts",
    needPath: true,
    filter: ["Indie X FM", "Kenny Arena", "Richard Latto"],
  },
  indy1033: {
    artist: "data.0.artist",
    song: "data.0.title",
    album: "data.0.album",
    stationName: "Indy 103.3",
    location: "Indianapolis, IN 🇺🇸",
    webUrl: "https://www.iheart.com/live/indy-1033-909/",
    streamUrl: "https://n44b-e2.revma.ihrhls.com/zc909",
    apiUrl: "https://ca.api.iheart.com/api/v3/live-meta/stream/909/trackHistory?limit=1",
    needPath: true,
    timestamp: "data.0.endTime",
  },
  inhailer: {
    stationName: "Inhailer Radio",
    albumArt: "iImg",
    location: "Cincinnati, OH 🇺🇸",
    webUrl: "https://inhailer.com",
    streamUrl: "https://streaming.radio.co/seac6e5991/listen",
    apiUrl: "https://scraper2.onlineradiobox.com/us.inhailer?l=0",
    timestamp: "updated",
    orbPath: true,
    filter: ["Inhailer", "WGUC", "At Brady", "Brady Music", "InLocal", "@INHAILERradio", "Taylor Fox", "Friday Vibe w", "FridayVibe", "Week-ender", "DJ Lou Freeman", "@Rootin", "Sledge, Sundays", "Elvis", "RareTodd", "Pete Riddle", "Music Festival", "Overtime With Jake", "Hitt List", " Ad", "James Burke", "Taft Theatre", " | ", "Ken The Lobby Boy"],
  },
  kexp: {
    artist: "results.0.artist",
    song: "results.0.song",
    album: "results.0.album",
    albumArt: "results.0.image_uri",
    stationName: "KEXP",
    location: "Seattle, WA 🇺🇸",
    webUrl: "https://kexp.org",
    streamUrl: "https://kexp.streamguys1.com/kexp160.aac",
    apiUrl: "https://api.kexp.org/v2/plays/?limit=1&format=json",
    timestamp: "results.0.airdate",
    needPath: true,
  },
  kcrw: {
    artist: "artist",
    song: "title",
    album: "album",
    albumArt: "albumImageLarge",
    stationName: "KCRW Eclectic 24",
    location: "Los Angeles, CA 🇺🇸",
    streamUrl: "https://kcrw.streamguys1.com/kcrw_192k_mp3_e24",
    apiUrl: "https://tracklist-api.kcrw.com/music",
    timestamp: "datetime",
  },
  krsm: {
    stationName: "KRSM",
    location: "Minneapolis, MN 🇺🇸",
    webUrl: "https://www.krsmradio.org/",
    streamUrl: "https://noasrv.caster.fm:10069/live",
    apiUrl: "https://widgets.spinitron.com/widget/now-playing-v2?callback=_spinitron05891577247031242171657762111&station=krsm&num=0&sharing=0&player=0&cover=0&merch=0&meta=0",
    stringPath: true,
    filter: ["KRSM"],
  },
  // Removing until they can actually put an SSL cert on their api, otherwise it doesn't work without the user enabling a security exemption
  // kusf: {
  //   artist: "Track.artist",
  //   song: "Track.title",
  //   album: "Track.album",
  //   stationName: "KUSF",
  //   location: "San Francisco, California 🇺🇸",
  //   webUrl: "https://kusf.org",
  //   streamUrl: "http://kusf.stream.creek.fm/stream",
  //   apiUrl: "http://www.kusf.org/api/broadcasting?limit=1",
  //   needPath: true,
  // },
  kutx: {
    artist: "onNow.song.artistName",
    song: "onNow.song.trackName",
    album: "onNow.song.collectionName",
    artist2: "tracklist.results.0.song.artistName",
    song2: "tracklist.results.0.song.trackName",  
    album2: "tracklist.results.0.song.collectionName",
    stationName: "KUTX",
    location: "Austin, TX 🇺🇸",
    webUrl: "https://kutx.org",
    streamUrl: "https://streams.kut.org/4428_56?aw_0_1st.playerid=kutx-free",
    apiUrl:
      "https://api.composer.nprstations.org/v1/widget/50ef24ebe1c8a1369593d032/tracks?format=json",
    needPath: true,
    altPath: true,
  },
  kxlu: {
    stationName: "KXLU",
    location: "Los Angeles, CA 🇺🇸",
    webUrl: "https://kxlu.com/",
    streamUrl: "https://kxlu.streamguys1.com/kxlu-hi",
    apiUrl: "https://widgets.spinitron.com/widget/now-playing-v2?callback=_spinitron206170750999458&station=kxlu&num=0&sharing=0&player=0&cover=1&merch=0&meta=0",
    stringPath: true,
    filter: ["KXLU", "Rickie Lee Jones"],
  },
  kxt: {
    artist: "0.artist",
    song: "0.song",
    album: "",
    stationName: "KXT",
    location: "Dallas, TX 🇺🇸",
    webUrl: "https://kxt.org",
    streamUrl: "https://kera.streamguys1.com/kxtlive128",
    apiUrl:
      "https://api.tunegenie.com/v2/brand/nowplaying/?apiid=m2g_bar&b=kkxt&format=json",
    timestamp: "0.played_at",
    needPath: true,
    filter: ["KXT"],
  },
  lemellotron: {
    artist: "artist",
    song: "title",
    album: "album",
    albumArt: "cover",
    stationName: "Le Mellotron",
    location: "Paris, France 🇫🇷",
    webUrl: "https://www.lemellotron.com/",
    streamUrl: "https://www.radioking.com/play/lemellotron-stream",
    apiUrl:
      "https://api.radioking.io/widget/radio/lemellotron-stream/track/current",
  },
  megashuffle: {
    stationName: "MegaShuffle",
    albumArt: "iImg",
    location: "Toronto, ON 🇨🇦",
    webUrl: "https://megashuffle.com",
    streamUrl: "https://maggie.torontocast.com:9028/stream",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.alternativerockvariety?l=0",
    timestamp: "updated",
    pathRegex: /^(.*?)\s*\-\s*(.*?)\s*(?:-\s*(.*))?$/g,
    orbPath: true,
    filter: ["MegaShuffle"],
  },
  metradio: {
    stationName: "Met Radio",
    location: "Toronto, ON 🇨🇦",
    webUrl: "https://metradio.ca",
    streamUrl: "https://ryerson.out.airtime.pro/ryerson_a",
    apiUrl: "https://widgets.spinitron.com/widget/now-playing-v2?callback=_spinitron05891577247031242171657762111&station=cjru&num=0&sharing=0&player=0&cover=1&merch=0&meta=0",
    stringPath: true,
    filter: ["Met Radio", "August 10", "devtunes"],
  },
// mtpr: {
//   artist: "onNow.song.artistName",
//   song: "onNow.song.trackName",
//   album: "onNow.song.collectionName",
//   artist2: "tracklist.results.0.song.artistName",
//   song2: "tracklist.results.0.song.trackName",  
//   album2: "tracklist.results.0.song.collectionName",
//   stationName: "Montana Public Radio",
//   location: "Butte, Montana 🇺🇸",
//   webUrl: "https://mtpr.org",
//   streamUrl: "https://25053.live.streamtheworld.com/KUFMFM.mp3",
//   apiUrl:
//     "https://api.composer.nprstations.org/v1/widget/5182a6b1e1c8386dfc2a9880/tracks?format=json",
//   timestamp: 'onNow.song._end_time',
//   timestamp2: 'tracklist.results.0.song._end_time',
//   needPath: true,
//   altPath: true,
// },
  plazaone: {
    artist: "song.artist",
    song: "song.title",
    album: "song.album",
    stationName: "Nightwave Plaza",
    albumArt: "song.artwork_src",
    location: "Internet",
    webUrl: "https://plaza.one/",
    streamUrl: "https://radio.plaza.one/mp3",
    apiUrl: "https://api.plaza.one/status",
    needPath: true,
  },
  qcindie: {
    stationName: "QCIndie",
    albumArt: "iImg",
    location: "Regina, SK 🇨🇦",
    webUrl: "https://qcindie.com",
    streamUrl: "https://stream.qcindie.com/live",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.qcindiecom?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  radiocaroline: {
    stationName: "Radio Caroline",
    albumArt: "iImg",
    location: "Essex, UK 🇬🇧",
    webUrl: "https://radiocaroline.co.uk",
    streamUrl: "http://sc6.radiocaroline.net:8000/;stream.nsv",
    apiUrl: "https://scraper2.onlineradiobox.com/uk.radiocaroline?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  radioparadisemain: {
    stationName: "Radio Paradise Main Mix",
    albumArt: "iImg",
    location: "Eureka, CA 🇺🇸",
    webUrl: "https://radioparadise.com/",
    streamUrl: "https://stream.radioparadise.com/mp3-192",
    apiUrl: "https://scraper2.onlineradiobox.com/us.radioparadise?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  radioparadiseglobal: {
    stationName: "Radio Paradise Global Mix",
    albumArt: "iImg",
    location: "Eureka, CA 🇺🇸",
    webUrl: "https://radioparadise.com/",
    streamUrl: "https://stream.radioparadise.com/world-etc-320",
    apiUrl: "https://scraper2.onlineradiobox.com/us.paradiseworldetcmix?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  radiosydney: {
    stationName: "Radio Sydney",
    albumArt: "iImg",
    location: "Sydney, Australia 🇦🇺",
    webUrl: "https://radio.sydney/",
    streamUrl: "https://cast3.asurahosting.com/proxy/radiosyd/stream",
    apiUrl: "https://scraper2.onlineradiobox.com/au.sydney128",
    timestamp: "updated",
    orbPath: true,
    flipMeta: true,
    pathRegex: /^(.*?)\s*-\s*(.*?)\s*(?:-\s*(.*))?$/g,
    filter: ["Radio Sydney"],
  },
  // radiowestern: {
  //   artist: "Artist",
  //   song: "Title",
  //   album: "Album",
  //   stationName: "Radio Western",
  //   location: "London, Ontario 🇨🇦",
  //   webUrl: "https://radiowestern.ca",
  //   streamUrl: "https://949fm.ca/stream",
  //   apiUrl: "https://radiowestern.ca:8000/latest",
  // },  
  radiox: {
    stationName: "Radio X",
    albumArt: "iImg",
    location: "London, UK 🇬🇧",
    webUrl: "https://radiox.co.uk",
    streamUrl: "https://media-ssl.musicradio.com/RadioXLondon",
    apiUrl: "https://scraper2.onlineradiobox.com/uk.radiox?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  indiepop: {
    artist: "songs.0.artist",
    song: "songs.0.title",
    album: "songs.0.album",
    stationName: "SomaFM Indie Pop Rocks!",
    location: "San Francisco, CA 🇺🇸",
    webUrl: "https://somafm.com",
    streamUrl: "https://ice5.somafm.com/indiepop-128-mp3",
    apiUrl: "https://somafm.com/songs/indiepop.json",
    timestamp: "songs.0.date",
    needPath: true,
  },
  socalsound: {
    stationName: "The SoCal Sound",
    albumArt: "iImg",
    location: "Los Angeles, CA 🇺🇸",
    webUrl: "https://thesocalsound.org/",
    streamUrl: "https://stream2.885fm.org/1",
    apiUrl: "https://scraper2.onlineradiobox.com/us.kcsn?l=0",
    timestamp: "updated",
    orbPath: true,
    filter: ["The SoCal Sound"],
  },
  soniccoast: {
    stationName: "The Sonic Coast",
    albumArt: "iImg",
    location: "Detroit, MI 🇺🇸",
    webUrl: "https://thesoniccoast.com/",
    streamUrl: "https://das-edge13-live365-dal02.cdnstream.com/a85042",
    apiUrl: "https://scraper2.onlineradiobox.com/us.thesoniccoast?l=0",
    timestamp: "updated",
    orbPath: true,
    filter: ["The Sonic Coast"],
  },
  thecurrent: {
    artist: "data.0.artist",
    song: "data.0.title",
    album: "data.0.album",
    stationName: "The Current",
    location: "Minneapolis, MN 🇺🇸",
    webUrl: "https://thecurrent.org",
    streamUrl: "https://current.stream.publicradio.org/current.aac",
    apiUrl:
      "https://ca.api.iheart.com/api/v3/live-meta/stream/6291/trackHistory?limit=1",
    needPath: true,
    updated: "data.0.endTime",
  },
  thebridge: {
    stationName: "The Bridge 90.9",
    albumArt: "iImg",
    location: "Kansas City, MO 🇺🇸",
    webUrl: "https://bridge909.org/",
    streamUrl: "https://live.amperwave.net/direct/publictv19-ktbgfmaac-imc1",
    apiUrl: "https://scraper2.onlineradiobox.com/us.ktbg?l=0",
    timestamp: "updated",
    orbPath: true,
    filter: ["The Bridge", "Sonic Spectrum"],
  },
  // thegamut: {
  //   artist: "data.response.0.data.artist",
  //   song: "data.response.0.data.description",
  //   album: "data.response.0.data.metadata.release_group.title",
  //   albumArt: "data.response.0.data.art_url",
  //   stationName: "The Gamut",
  //   location: "Frederick, Maryland 🇺🇸",
  //   webUrl: "https://thegamut.fm",
  //   streamUrl: "https://22113.live.streamtheworld.com/WWFDAMAAC.aac",
  //   apiUrl: "https://live.gamut.fm/wp-content/plugins/hubbard-listen-live/api/hll_cues_get.php?format=json",
  //   timestamp: "data.response.0.timestamp",
  //   needPath: true,  
  // },
  tmm: {
    stationName: "The Music Machine",
    albumArt: "iImg",
    location: "London, UK 🇬🇧",
    webUrl: "https://www.themusicmachine.co.uk/",
    streamUrl: "https://msmn3.co/proxy/x1mp33/stream",
    apiUrl: "https://scraper2.onlineradiobox.com/uk.themusicmachine1?l=0",
    timestamp: "updated",
    orbPath: true,
    filter: ["AD START"],
  },
  thesummit: {
    stationName: "The Summit",
    location: "Akron, OH 🇺🇸",
    webUrl: "https://thesummit.fm",
    streamUrl: "https://securestreams2.autopo.st:1194/wapshq",
    apiUrl: "https://thesummit.fm/playlist-app/getP1CurrentSong.php",
    stringPath: true,
    phpString: true,
    pathRegex: /"([^"]+)\s-\s([^"]+)"/,
    filter: ["The Summit", "thesummit"],
  },
  triplejunearthed: {
    stationName: "Triple J Unearthed",
    albumArt: "iImg",
    location: "Sydney, Australia 🇦🇺",
    webUrl: "https://www.abc.net.au/triplejunearthed/",
    streamUrl: "https://live-radio01.mediahubaustralia.com/UNEW/mp3/",
    apiUrl: "https://scraper2.onlineradiobox.com/au.abctriplejunearthed?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  wbfo: {
    stationName: "WBFO - The Bridge",
    albumArt: "iImg",
    location: "Buffalo, NY 🇺🇸",
    webUrl: "https://www.wbfo.org/the-bridge",
    streamUrl: "https://17633.live.streamtheworld.com/WBFO_THE_BRIDGEAAC.aac",
    apiUrl: "https://scraper2.onlineradiobox.com/us.thebridge?l=0",
    timestamp: "updated",
    orbPath: true,
    filter: ["WBFO", "The Bridge"],
  },
  wbru: {
    stationName: "WBRU",
    albumArt: "iImg",
    location: "Providence, RI 🇺🇸",
    webUrl: "https://wbru.com",
    streamUrl: "https://s3.radio.co/s115121de1/listen",
    apiUrl: "https://scraper2.onlineradiobox.com/us.wbru?l=0",
    timestamp: "updated",
    orbPath: true,
    filter: ["WBRU", "Providence"],
  },
  wber: {
    stationName: "WBER",
    location: "Penfield, NY 🇺🇸",
    webUrl: "https://wber.org/",
    streamUrl: "https://radio.monroe.edu/wber.mp3",
    apiUrl: "https://widgets.spinitron.com/widget/now-playing-v2?callback=_spinitron206170750999458&station=wber&num=0&sharing=0&player=0&cover=1&merch=0&meta=0",
    stringPath: true,
    filter: ["WLUW"],
  },
  wbor: {
    stationName: "WBOR",
    location: "Brunswick, ME 🇺🇸",
    webUrl: "https://wbor.org/",
    streamUrl: "https://listen.wbor.org/",
    apiUrl: "https://widgets.spinitron.com/widget/now-playing-v2?callback=_spinitron206170750999458&station=wbor&num=0&sharing=0&player=0&cover=1&merch=0&meta=0",
    stringPath: true,
    filter: ["WBOR"],
  },
  wers: {
    stationName: "WERS",
    albumArt: "iImg",
    location: "Boston, MA 🇺🇸",
    webUrl: "https://wers.org",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/WERSFMAAC.aac",
    apiUrl: "https://scraper2.onlineradiobox.com/us.wers?l=0",
    timestamp: "updated",
    orbPath: true,
    filter: ["WERS", "Emerson", "Volante Evergreen", "SRO SP"],
  },
  wfpk: {
    stationName: "WFPK",
    albumArt: "iImg",
    location: "Louisville, KY 🇺🇸",
    webUrl: "https://www.lpm.org/music",
    streamUrl: "https://lpm.streamguys1.com/wfpk-popup?uuid=26x8rb0vc",
    apiUrl: "https://scraper2.onlineradiobox.com/us.wfpk?l=0",
    timestamp: "updated",
    orbPath: true,
    filter: ["WFPK"],
  },
  wfmu: {
    stationName: "WFMU",
    albumArt: "iImg",
    location: "Jersey City, NJ 🇺🇸",
    webUrl: "https://wfmu.org",
    streamUrl: "https://stream0.wfmu.org/freeform-128k.mp3",
    apiUrl: "https://scraper2.onlineradiobox.com/us.wfmu?l=0",
    timestamp: "updated",
    orbPath: true,
    pathRegex: /"([^"]+)" by ([^"]+?)(?=\son)/,
    flipMeta: true,
    filter: ["on Wake on WFMU", "Your DJ speaks", "Cat Bomb! Radio", "Six Degrees with Alan"],

  },
  wfuv: {
    stationName: "WFUV",
    albumArt: "iImg",
    location: "New York, NY 🇺🇸",
    webUrl: "https://wfuv.org",
    streamUrl: "https://music.wfuv.org/music-hi",
    apiUrl: "https://scraper2.onlineradiobox.com/us.wfuvhd2?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  wicb: {
    stationName: "WICB",
    artist: "0.artist",
    song: "0.title",
    album: "0.album",
    albumArt: "0.art_url",
    location: "New York, NY 🇺🇸",
    webUrl: "https://wfuv.org",
    streamUrl: "https://icecast.do.zufall.co/wicb_aac_high",
    apiUrl: "https://api-v2.wicb.org/song/history/WICB?limit=1",
    timestamp: "0.timestamp",
    needPath: true,
  },
  wluw: {
    stationName: "WLUW",
    location: "Chicago, IL 🇺🇸",
    webUrl: "https://wluw.org/",
    streamUrl: "https://wluw.streamguys1.com/stream.mp3",
    apiUrl: "https://widgets.spinitron.com/widget/now-playing-v2?callback=_spinitron206170750999458&station=wluw&num=0&sharing=0&player=0&cover=1&merch=0&meta=0",
    stringPath: true,
    filter: ["WLUW"],
  },
  wmse: {
    stationName: "WMSE Radio",
    albumArt: "iImg",
    location: "Milwaukee, WI 🇺🇸",
    webUrl: "https://wmse.org",
    streamUrl: "https://wmse.streamguys1.com/wmselivemp3",
    apiUrl: "https://scraper2.onlineradiobox.com/us.wmse?l=0",
    timestamp: "updated",
    orbPath: true,
    flipMeta: true,
    pathRegex: /^([^"]+)\s+by\s+([^"]+)/,
    filter: ["WMSE", "Milwaukee", "Armed Fauxes Radio with Kelly Aiglon"],
  },
  wnrn: {
    stationName: "WNRN",
    albumArt: "iImg",
    location: "Charlottesville, VA 🇺🇸",
    webUrl: "https://wnrn.org",
    streamUrl: "https://26223.live.streamtheworld.com/WNRNFM_128.mp3",
    apiUrl: "https://scraper2.onlineradiobox.com/us.w276bz?l=0",
    timestamp: "updated",
    orbPath: true,
    filter: ["WNRN", "In-Studio Session"],
  },
  wnxp: {
    artist: "0.artist",
    song: "0.song",
    album: "",
    stationName: "WNXP",
    location: "Nashville, TN 🇺🇸",
    webUrl: "https://wnxp.org",
    streamUrl: "https://wpln.streamguys1.com/wnxpfm.aac",
    apiUrl:
      "https://api.tunegenie.com/v2/brand/nowplaying/?apiid=m2g_bar&b=wnxp&format=json",
    timestamp: "0.played_at",
    needPath: true,
  },
  wpkn: {
    stationName: "WPKN",
    location: "Bridgeport, CT 🇺🇸",
    webUrl: "https://wpkn.org/",
    streamUrl: "http://live.adsciconsolidated.com/wpknhigh.mp3",
    apiUrl: "https://widgets.spinitron.com/widget/now-playing-v2?callback=_spinitron206170750999458&station=wpkn&num=0&sharing=0&player=0&cover=1&merch=0&meta=0",
    stringPath: true,
    filter: ["WKPN"],
  },
  wrir: {
    stationName: "WRIR",
    location: "Richmond, VA 🇺🇸",
    webUrl: "https://wrir.org/",
    streamUrl: "https://live.wrir.org/",
    apiUrl: "https://widgets.spinitron.com/widget/now-playing-v2?callback=_spinitron206170750999458&station=wrir&num=0&sharing=0&player=0&cover=1&merch=0&meta=0",
    stringPath: true,
    filter: ["WRIR"],
  },
  wtmd: {
    stationName: "WTMD",
    albumArt: "iImg",
    location: "Baltimore, MD 🇺🇸",
    webUrl: "https://wtmd.org",
    streamUrl: "https://wtmd-ice.streamguys1.com/wtmd.mp3",
    apiUrl: "https://scraper2.onlineradiobox.com/us.wtmd?l=0",
    timestamp: "updated",
    orbPath: true,
    flipMeta: true,
    filter: ["WTMD", "6 Degrees of Soul", "Brooks Long"],
  },
  wyomingsounds: {
    albumArt: "iImg",
    stationName: "Wyoming Sounds",
    location: "Laramie, WY 🇺🇸",
    webUrl: "https://www.wyomingpublicmedia.org",
    streamUrl: "https://wyoming-public-ice.streamguys1.com/WYS128MP3?uuid=qfbe7zumo",
    apiUrl: "https://scraper2.onlineradiobox.com/us.kuwe",
    pathRegex: /(.+?)\s*-\s*(.+?)\s*-\s*.*/,
    orbPath: true,
    flipMeta: true,
  },
  wyep: {
    artist: "onNow.song.artistName",
    song: "onNow.song.trackName",
    album: "onNow.song.collectionName",
    artist2: "tracklist.results.0.song.artistName",
    song2: "tracklist.results.0.song.trackName",
    stationName: "WYEP",
    location: "Pittsburgh, PA 🇺🇸",
    webUrl: "https://wyep.org/",
    streamUrl: "https://ais-sa3.cdnstream1.com/2557_128.mp3",
    apiUrl:
      "https://api.composer.nprstations.org/v1/widget/50e451b6a93e91ee0a00028e/tracks?format=json&limit=1",
    needPath: true,
    altPath: true,
    filter: ["WYEP"],
  },
  wyms: {
    artist: "data.0.artist",
    song: "data.0.title",
    album: "data.0.album",
    stationName: "88Nine",
    location: "Milwaukee, WI 🇺🇸",
    webUrl: "https://www.radiomilwaukee.org/",
    streamUrl: "https://wyms.streamguys1.com/live?platform=88nine",
    apiUrl: "https://ca.api.iheart.com/api/v3/live-meta/stream/8380/trackHistory?limit=1",
    needPath: true,
    timestamp: "data.0.endTime",
  },
  xpn: {
    stationName: "XPN",
    albumArt: "iImg",
    location: "Philiadelphia, PA 🇺🇸",
    webUrl: "https://wxpn.org",
    streamUrl: "https://wxpnhi.xpn.org/xpnhi-nopreroll",
    apiUrl: "https://scraper2.onlineradiobox.com/us.wxpn?l=0",
    timestamp: "updated",
    orbPath: true,
    filter: ["World Cafe"],
  },
  xpn2: {
    stationName: "XPN2",
    albumArt: "iImg",
    location: "Philiadelphia, PA 🇺🇸",
    webUrl: "https://wxpn.org",
    streamUrl: "https://wxpnhi.xpn.org/xpn2hi-nopreroll",
    apiUrl: "https://scraper2.onlineradiobox.com/us.wxpnhd2?l=0",
    timestamp: "updated",
    orbPath: true,
    filter: ["World Cafe"],
  },
  ynotradio: {
    stationName: "Y-Not Radio",
    albumArt: "iImg",
    location: "Philiadelphia, PA 🇺🇸",
    webUrl: "https://www.ynotradio.net/",
    streamUrl: "https://streaming.live365.com/a54553",
    apiUrl: "https://scraper2.onlineradiobox.com/us.iradiophillynot?l=0",
    timestamp: "updated",
    orbPath: true,
  },
};
