const stations = {
  amazingradiouk: {
    artist: "included.1.attributes.radio_artist",
    song: "included.1.attributes.radio_name",
    album: "",
    albumArt: "included.1.attributes.image_urls.large",
    stationName: "Amazing Radio UK",
    location: "Newcastle, United Kingdom",
    webUrl: "https://amazingradio.com",
    streamUrl: "https://stream.amazingradio.com:8443/stream.mp3?ngsw-bypass",
    apiUrl: "https://api.amazingtunes.com/radio/uk/airplays?page[size]=1&include[]=tune&include[]=tune.artist",
    needPath: true,
  },  
  amazingradious: {
    artist: "included.1.attributes.radio_artist",
    song: "included.1.attributes.radio_name",
    album: "",
    albumArt: "included.1.attributes.image_urls.large",
    stationName: "Amazing Radio US",
    location: "United States",
    webUrl: "https://amazingradio.com",
    streamUrl: "https://stream3.amazingradio.us:8443/stream.mp3?redirected=1",
    apiUrl: "https://api.amazingtunes.com/radio/us/airplays?page[size]=1&include[]=tune&include[]=tune.artist",
    needPath: true,
  }, 
  bagelradio: {
    stationName: "Bagel Radio",
    location: "Forest Hills, New York, USA",
    webUrl: "https://www.bagelradio.com",
    streamUrl: "https://ais-sa3.cdnstream1.com/2606_128.aac",
    apiUrl: "https://scraper2.onlineradiobox.com/us.bagel?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  bbcradio6: {
    combined: "title",
    artist: "iArtist",
    song: "iName",
    album: "",
    albumArt: "iImg",
    stationName: "BBC6 Radio",
    location: "London, UK",
    webUrl: "https://www.bbc.co.uk/sounds/play/live:bbc_6music",
    streamUrl: "https://as-hls-ww.live.cf.md.bbci.co.uk/pool_904/live/ww/bbc_6music/bbc_6music.isml/bbc_6music-audio%3d96000.norewind.m3u8",
    apiUrl: "https://scraper2.onlineradiobox.com/uk.bbcradio6?l=0",
    timestamp: "updated",
    pathRegex: /^(.*?)s*-s*(.*?)$/,
    orbPath: true,
  },  
  birchstreet: {
    artist: "iArtist",
    song: "iName",
    album: "",
    albumArt: "iImg",
    stationName: "Birch Street Radio",
    location: "Richmond Hill, Ontario, Canada",
    webUrl: "https://www.birchstreetradio.com",
    streamUrl: "https://jenny.torontocast.com:8172/stream",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.birchstreet?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  chillfiltr: {
    stationName: "CHILLFILTR",
    albumArt: "iImg",
    location: "Ottawa, Ontario, Canada",
    webUrl: "https://www.chillfiltr.com",
    streamUrl: "https://ais-edge102-live365-dal02.cdnstream.com/a80518",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.chillfiltr?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  cjiq: {
    stationName: "CJIQ",
    albumArt: "iImg",
    location: "Kitchener, Ontario, Canada",
    webUrl: "https://www.cjiqfm.com",
    streamUrl: "https://conestoga.leanstream.co/CJIQFM",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.cjiq",
    timestamp: "updated",
    orbPath: true,
    flipMeta: true,
  },
  ckua: {
    artist: "0.TPE1",
    song: "0.TIT2",
    album: "0.TALB",
    stationName: "CKUA",
    location: "Edmonton, Alberta, Canada",
    webUrl: "https://www.ckua.com",
    streamUrl: "https://ais-sa1.streamon.fm/7000_48k.aac",
    apiUrl:
      "https://yp.cdnstream1.com/metadata/7000_48k/current.json?cb=308869",
    needPath: true,
  },
  flashAlt: {
    stationName: "Flashback Alternatives",
    albumArt: "iImg",
    location: "Toronto, Ontario, Canada",
    webUrl: "https://flashbackalternatives.com/",
    streamUrl: "https://puma.streemlion.com:1225/stream",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.falternatives",
    timestamp: "updated",
    pathRegex: /^(.*?)\s*-\s*(.*?)\s*-/,
    orbPath: true,
  },
  gorillafm: {
    stationName: "Gorilla FM",
    location: "Zug, Switzerland",
    albumArt: "iImg",
    webUrl: "https://www.1.fm/station/gorillafm",
    streamUrl: "https://strm112.1.fm/gorillafm_mobile_mp3",
    apiUrl: "https://scraper2.onlineradiobox.com/ch.1fmgorillafmradio?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  indie1023: {
    artist: "0.artist",
    song: "0.title",
    album: "0.album",
    stationName: "Indie 102.3",
    location: "Denver, Colorado, USA",
    webUrl: "https://indie1023.org",
    streamUrl: "https://stream1.cprnetwork.org/cpr3_lo",
    apiUrl: "https://playlist.cprnetwork.org/won_plus3/KVOQ.json",
    needPath: true,
  },
  indie88: {
    stationName: "Indie88",
    albumArt: "iImg",
    location: "Toronto, Ontario, Canada",
    webUrl: "https://indie88.com",
    streamUrl: "https://cob-ais.leanstream.co/CINDFM-MP3",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.cind?l=0",
    timestamp: "updated",
    orbPath: true,
    flipMeta: true,
  },
  indieradio: {
    artist: "data.0.artist",
    song: "data.0.title",
    album: "data.0.album",
    stationName: "IHeartRadio Indie Radio",
    location: "USA",
    webUrl: "https://www.iheart.com/live/indie-radio-7189/",
    streamUrl: "https://n22b-e2.revma.ihrhls.com/zc7189?rj-ttl=5&rj-tok=AAABjcTTelwApoP4JWMpy18HgQ",
    apiUrl: "https://ca.api.iheart.com/api/v3/live-meta/stream/7189/trackHistory?limit=1",
    needPath: true,
  },
  indiexfm: {
    artist: "results.0.author",
    song: "results.0.title",
    album: "results.0.album",
    albumArt: "results.0.img_large_url",
    stationName: "Indie X FM",
    location: "Los Angeles, California, USA",
    webUrl: "https://indiexfm.com/",
    streamUrl: "https://kathy.torontocast.com:2145/stream",
    apiUrl: "https://kathy.torontocast.com:1150/api/v2/history/?limit=1&offset=0&server=1&format=json",
    needPath: true,
  },
  indy1033: {
    artist: "data.0.artist",
    song: "data.0.title",
    album: "data.0.album",
    stationName: "Indy 103.3",
    location: "USA",
    webUrl: "https://www.iheart.com/live/indie-radio-7189/",
    streamUrl: "https://n11b-e2.revma.ihrhls.com/zc909?rj-ttl=5&rj-tok=AAABjcTbcowAYWjGuBpPhrnfPQ",
    apiUrl: "https://ca.api.iheart.com/api/v3/live-meta/stream/909/trackHistory?limit=1",
    needPath: true,
  },
  kexp: {
    artist: "results.0.artist",
    song: "results.0.song",
    album: "results.0.album",
    albumArt: "results.0.image_uri",
    stationName: "KEXP",
    location: "Seattle, Washington, USA",
    webUrl: "https://kexp.org",
    streamUrl: "https://kexp.streamguys1.com/kexp160.aac",
    apiUrl: "https://api.kexp.org/v2/plays/?limit=1",
    needPath: true,
  },
  kcrw: {
    artist: "artist",
    song: "title",
    album: "album",
    albumArt: "albumImageLarge",
    stationName: "KCRW",
    location: "Los Angeles, California, USA",
    streamUrl: "https://kcrw.streamguys1.com/kcrw_192k_mp3_e24",
    apiUrl: "https://tracklist-api.kcrw.com/music",
    timestamp: "datetime",
  },
  kusf: {
    artist: "Track.artist",
    song: "Track.title",
    album: "Track.album",
    stationName: "KUSF",
    location: "San Francisco, California, USA",
    webUrl: "https://kusf.org",
    streamUrl: "https://kusf.stream.creek.fm/stream",
    apiUrl: "https://www.kusf.org/api/broadcasting?limit=1",
    needPath: true,
  },
  kutx: {
    artist: "onNow.song.artistName",
    song: "onNow.song.trackName",
    album: "onNow.song.collectionName",
    stationName: "KUTX",
    location: "Austin, Texas, USA",
    webUrl: "https://kutx.org",
    streamUrl: "https://kut.streamguys1.com/kutx-web",
    apiUrl:
      "https://api.composer.nprstations.org/v1/widget/50ef24ebe1c8a1369593d032/tracks?format=json",
    needPath: true,
  },
  lemellotron: {
    artist: "artist",
    song: "title",
    album: "album",
    albumArt: "cover",
    stationName: "Le Mellotron",
    location: "Global",
    webUrl: "https://www.lemellotron.com/",
    streamUrl: "https://www.radioking.com/play/lemellotron-stream",
    apiUrl:
      "https://api.radioking.io/widget/radio/lemellotron-stream/track/current",
  },
  qcindie: {
    stationName: "QCIndie",
    location: "Regina, Saskatchewan, Canada",
    webUrl: "https://qcindie.com",
    streamUrl: "https://stream.qcindie.com/live",
    apiUrl: "https://scraper2.onlineradiobox.com/ca.qcindiecom?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  radioparadisemain: {
    stationName: "Radio Paradise Main Mix",
    location: "Eureka, California, USA",
    webUrl: "https://radioparadise.com/",
    streamUrl: "https://stream.radioparadise.com/mp3-192",
    apiUrl: "https://scraper2.onlineradiobox.com/us.radioparadise?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  radioparadiseglobal: {
    stationName: "Radio Paradise Global Mix",
    location: "Eureka, California, USA",
    webUrl: "https://radioparadise.com/",
    streamUrl: "https://stream.radioparadise.com/world-etc-320",
    apiUrl: "https://scraper2.onlineradiobox.com/us.paradiseworldetcmix?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  indiepop: {
    artist: "songs.0.artist",
    song: "songs.0.title",
    album: "songs.0.album",
    stationName: "SomaFM Indie Pop Rocks!",
    location: "San Francisco, California, USA",
    webUrl: "https://somafm.com",
    streamUrl: "https://ice5.somafm.com/indiepop-128-mp3",
    apiUrl: "https://somafm.com/songs/indiepop.json",
    needPath: true,
  },
  thecurrent: {
    artist: "data.0.artist",
    song: "data.0.title",
    album: "data.0.album",
    stationName: "The Current",
    location: "Minneapolis, Minnesota, USA",
    webUrl: "https://thecurrent.org",
    streamUrl: "https://current.stream.publicradio.org/current.aac",
    apiUrl:
      "https://ca.api.iheart.com/api/v3/live-meta/stream/6291/trackHistory?limit=1",
    needPath: true,
  },
  thesummit: {
    artist: "",
    song: "",
    album: "",
    stationName: "The Summit",
    location: "Akron, Ohio, USA",
    webUrl: "https://thesummit.fm",
    streamUrl: "https://securestreams2.autopo.st:1194/wapshq",
    apiUrl: "https://thesummit.fm/playlist-app/getP1CurrentSong.php",
    stringPath: true,
    pathRegex: /^(.*?)s*-s*(.*?)$/,
  },
  wbfo: {
    artist2: "onNow.song.artistName",
    song2: "onNow.song.trackName",
    artist: "tracklist.results.0.song.artistName",
    song: "tracklist.results.0.song.trackName",
    stationName: "WBFO - The Bridge",
    location: "Buffalo, New York, USA",
    webUrl: "https://www.wbfo.org/the-bridge",
    streamUrl: "https://14553.live.streamtheworld.com/WBFO_THE_BRIDGEAAC.aac",
    apiUrl:
      "https://api.composer.nprstations.org/v1/widget/5a679ab2e4b0f3ec69154c59/tracks?format=json&limit=2&hide_amazon=false&hide_itunes=false&hide_arkiv=false&share_format=false",
    needPath: true,
    nprPath: true,
    streamNotes: "This api is super tempermental. I've observed it stop working on Saturday night at midnight, then resume on Monday a couple times. Not sure if it's a bug on their part."
  },
  wbru: {
    stationName: "WBRU",
    albumArt: "iImg",
    location: "Providence, Rhode Island, USA",
    webUrl: "https://wbru.com",
    streamUrl: "https://s3.radio.co/s115121de1/listen",
    apiUrl: "https://scraper2.onlineradiobox.com/us.wbru?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  wfpk: {
    artist: "onNow.song.artistName",
    song: "onNow.song.trackName",
    artist2: "tracklist.results.0.song.artistName",
    song2: "tracklist.results.0.song.trackName",
    stationName: "WFPK - Louisville Public Media Music",
    location: "Louisville, Kentucky, USA",
    webUrl: "https://www.lpm.org/music",
    streamUrl: "https://lpm.streamguys1.com/wfpk-popup?uuid=26x8rb0vc",
    apiUrl:
      "https://api.composer.nprstations.org/v1/widget/51929bfde1c8886d5ccfb1d9/tracks?format=json&limit=2&hide_amazon=false&hide_itunes=false&hide_arkiv=false&share_format=false",
    needPath: true,
    nprPath: true,
  },
  wfuv: {
    stationName: "WFUV",
    albumArt: "iImg",
    location: "New York, New York, USA",
    webUrl: "https://wfuv.org",
    streamUrl: "https://onair.wfuv.org/onair-hi",
    apiUrl: "https://scraper2.onlineradiobox.com/us.wfuv?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  wnxp: {
    artist: "0.artist",
    song: "0.song",
    album: "",
    stationName: "WNXP",
    location: "Nashville, Tennessee, USA",
    webUrl: "https://wnxp.org",
    streamUrl: "https://wpln.streamguys1.com/wnxpfm.aac",
    apiUrl:
      "https://api.tunegenie.com/v2/brand/nowplaying/?apiid=m2g_bar&b=wnxp&format=json",
    timestamp: "0.played_at",
    needPath: true,
  },
  wyomingsounds: {
    albumArt: "iImg",
    stationName: "Wyoming Sounds",
    location: "Laramie, Wyoming, USA",
    webUrl: "https://www.wyomingpublicmedia.org",
    streamUrl: "https://wyoming-public-ice.streamguys1.com/WYS128MP3?uuid=qfbe7zumo",
    apiUrl: "https://scraper2.onlineradiobox.com/us.kuwe",
    orbPath: true,
  },
  wxpn: {
    stationName: "XPN",
    albumArt: "iImg",
    location: "Philiadelphia, Pennsylvania, USA",
    webUrl: "https://wxpn.org",
    streamUrl: "https://wxpnhi.xpn.org/xpnhi-nopreroll",
    apiUrl: "https://scraper2.onlineradiobox.com/us.wxpn?l=0",
    timestamp: "updated",
    orbPath: true,
  },
  wyep: {
    artist: "onNow.song.artistName",
    song: "onNow.song.trackName",
    artist2: "tracklist.results.0.song.artistName",
    song2: "tracklist.results.0.song.trackName",
    stationName: "WYEP",
    location: "Pittsburgh, Pennsylvania, USA",
    webUrl: "https://wyep.org/",
    streamUrl: "https://ais-sa3.cdnstream1.com/2557_128.mp3",
    apiUrl:
      "https://api.composer.nprstations.org/v1/widget/50e451b6a93e91ee0a00028e/tracks?format=json&limit=1",
    needPath: true,
    nprPath: true,
  },
  wyms: {
    artist: "data.0.artist",
    song: "data.0.title",
    album: "data.0.album",
    stationName: "88Nine",
    location: "Milwaukee, Wisconsin, USA",
    webUrl: "https://www.radiomilwaukee.org/",
    streamUrl: "https://wyms.streamguys1.com/live?platform=88nine",
    apiUrl: "https://ca.api.iheart.com/api/v3/live-meta/stream/8380/trackHistory?limit=1",
    needPath: true,
  },
};
