const stationData = {
  inhailer: {
    stationName: "Inhailer Radio",
    albumArt: "data.artwork_urls.large",
    location: "Cincinnati, OH 🇺🇸",
    webUrl: "https://inhailer.com",
    streamUrl: "https://streaming.radio.co/seac6e5991/listen",
    apiUrl: "https://public.radio.co/api/v2/seac6e5991/track/current",
    timestamp: "data.start_time",
    timezone: "America/New_York",
    dataPath: true,
    filter: [
      "Inhailer",
      "WGUC",
      "At Brady",
      "Brady Music",
      "InLocal",
      "@INHAILERradio",
      "Taylor Fox",
      "Friday Vibe w",
      "FridayVibe",
      "Week-ender",
      "DJ Lou",
      "@Rootin",
      "Sledge, Sundays",
      "Elvis",
      "RareTodd",
      "Pete Riddle",
      "Music Festival",
      "Overtime With Jake",
      "Hitt List",
      " Ad",
      "James Burke",
      "Taft Theatre",
      " | ",
      "Ken The Lobby Boy",
      ".com",
      "Nils The Music Director",
      "Josh Tillman",
      "New Music Showcase",
      "Toyota",
      "at Woodward",
      "Indie 500",
      "At The Columbia",
      "Work Release Program",
      "at Madison Rooftop",
      "97x",
      "DJ Andy Eckerle",
      "James Burke",
      "Lauren Fitzpatrick",
      "Ethan Bloomfield",
      "Ethan in the",
      "http",
      "www",
      " PM",
      " AM",
      "Clara Stryker"
    ],
  },
}
