const stationData = {
  kalw: {
    artist: "onNow.song.artistName",
    song: "onNow.song.trackName",
    album: "onNow.song.collectionName",
    artist2: "tracklist.results.0.song.artistName",
    song2: "tracklist.results.0.song.trackName",
    album2: "tracklist.results.0.song.collectionName",
    stationName: "KALW",
    location: "San Francisco, CA 🇺🇸",
    webUrl: "https://kalw.org",
    streamUrl: "https://kalw-live.streamguys1.com/kalw.aac?uuid=jfpdzfzx",
    nprPath: "51827f44e1c8e597ac3f8461",
    duration: "onNow.song._duration",
    duration2: "tracklist.results.0.song._duration",
    timestamp: "onNow.song._start_time",
    timestamp2: "tracklist.results.0.song._start_time",
    timezone: "America/Chicago",
    altPath: true,
  },
}
