const stationData = {
  kutx: {
    artist: "onNow.song.artistName",
    song: "onNow.song.trackName",
    album: "onNow.song.collectionName",
    artist2: "tracklist.results.0.song.artistName",
    song2: "tracklist.results.0.song.trackName",
    album2: "tracklist.results.0.song.collectionName",
    stationName: "KUTX",
    location: "Austin, TX 🇺🇸",
    webUrl: "https://kutx.org",
    streamUrl: "https://streams.kut.org/4428_56?aw_0_1st.playerid=kutx-free",
    nprPath: "50ef24ebe1c8a1369593d032",
    duration: "onNow.song._duration",
    duration2: "tracklist.results.0.song._duration",
    timestamp: "onNow.song._start_time",
    timestamp2: "tracklist.results.0.song._start_time",
    timezone: "America/Chicago",
    altPath: true,
  },
}
