name: cPanel Deployment

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to cPanel FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.CPANEL_FTP_PATH }}
        username: ${{ secrets.CPANEL_FTP_USER }}
        password: ${{ secrets.CPANEL_FTP_PASSWORD }}
        # local-dir: <local github folder -- use ./ for repository root>
        local-dir: ./
        # server-dir: <remote_dir -- use / for root>
        server-dir: /
        protocol: ftps
        security: strict
        dry-run: false
    - name: Purge cache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        # Zone is required by both authentication methods
        CLOUDFLARE_ZONE: '${{ secrets.CLOUDFLARE_ZONE }}'
        CLOUDFLARE_TOKEN: '${{ secrets.CLOUDFLARE_TOKEN }}'
