name: cPanel Deployment

on:
 push:
   branches:
     - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Sync files to cPanel via Rsync
        uses: easingthemes/ssh-deploy@main
        env:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         SSH_PORT: ${{ secrets.CPANEL_HOST_PORT }}
         ARGS: "-rlgoDzvc -i --delete"
         REMOTE_HOST: ${{ secrets.CPANEL_HOST_URL }}
         REMOTE_USER: ${{ secrets.CPANEL_USERNAME }}
         TARGET: ${{ secrets.CPANEL_REMOTE_PATH }}
      - name: Purge Cloudflare Cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
