name: cPanel Deployment

on:
  push:
    branches:
      - main
jobs:
    deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel
        id: deploy
        uses: pinkasey/cpanel-deploy-action@v1.0.0
        with:
          hostname: '${{ secrets.CPANEL_HOSTING_URL }}'
          repository_root: '${{ secrets.CPANEL_REMOTE_PATH }}'
          branch: main
          cpanel_token: '${{ secrets.CPANEL_TOKEN }}'
          cpanel_username: '${{ secrets.CPANEL_USERNAME }}'
      - name: echo deploy-duration
        run: echo "Deployment took ${{ steps.deploy.outputs.duration }} milliseconds"
      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          # Zone is required by both authentication methods
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
