name: cPanel Deployment

on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy:
    name: FTP-Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: '${{ secrets.CPANEL_HOSTING_URL }}'
        user: '${{ secrets.CPANEL_FTP_USER }}'
        password: '${{ secrets.CPANEL_FTP_PASSWORD }}'
        localDir: '${{ secrets.CPANEL_REMOTE_PATH }}'
    - name: Purge cache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        # Zone is required by both authentication methods
        CLOUDFLARE_ZONE: '${{ secrets.CLOUDFLARE_ZONE }}'
        CLOUDFLARE_TOKEN: '${{ secrets.CLOUDFLARE_TOKEN }}'
